# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20161123_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='Money',
            field=models.FileField(blank=True, upload_to='', verbose_name='Смета проекта'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='Project',
            field=models.FileField(blank=True, upload_to='attachments', verbose_name='Проект'),
        ),
    ]
