# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20161123_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='CV',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='Money',
        ),
    ]
