# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_auto_20161123_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='Project',
            new_name='attachments',
        ),
    ]
