# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_auto_20161123_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='attachment_02',
            field=models.FileField(blank=True, upload_to='attachments'),
        ),
        migrations.AddField(
            model_name='apply',
            name='attachment_03',
            field=models.FileField(blank=True, upload_to='attachments'),
        ),
    ]
